#rabbitmq:
#  image: rabbitmq:management
#  ports:
#    - "5672:5672"
#    - "15672:15672"

version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
