server.port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:compoundinterest;INIT=CREATE SCHEMA IF NOT EXISTS compound_interest
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: compound_interest
        format_sql: true
        jakarta.persistence.sharedCache.mode: UNSPECIFIED
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    VirtualHost: /
api.event:
  exchange: loan.exchange
  payment:
    confirmation:
      routing-key: payment.confirmation
      queue: payment.confirmation.queue
      error:
        ttl: 10000

